[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.3.0"

[[constraint]]
  name = "github.com/golang/protobuf"
  branch = "master"

[[constraint]]
  name = "golang.org/x/net"
  branch = "master"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.7.1"

[[override]]
  name = "rsc.io/letsencrypt"
  source = "https://github.com/dmcgowan/letsencrypt.git"
  revision = "e770c10b0f1a64775ae91d240407ce00d1a5bdeb"

[[override]]
  name = "github.com/yvasiyarov/gorelic"
  version = "0.0.6"

[[override]]
  name = "github.com/yvasiyarov/newrelic_platform_go"
  revision = "b21fdbd4370f3717f3bbd2bf41c223bc273068e6"

[[override]]
  name = "github.com/xenolf/lego"
  revision = "a9d8cec0e6563575e5868a005359ac97911b5985"

[[override]]
  name = "github.com/miekg/dns"
  version = "=1.0.15"
